In [1]:
"""Domanda 2 (Sistemi lineari). Dato un problema test di dimensioni variabili
                                    Ax = b
la cui soluzione esatta è il vettore x̄ = (1, . . . , 1)T e b è il termine noto, ottenuto 
come Ax̄ calcolare:
    • il numero di condizionamento della matrice A
    • la soluzione x del sistema lineare Ax = b mediante la fattorizzazione di Cholesky
Considerare come matrice A la matrice tridiagonale simmetrica definita positiva, avente 
sulla diagonale principale elementi uguali a 9 ed elementi nella sopra e sottodiagonale 
uguali a -4, con n variabile."""
import numpy as np
from numpy.linalg import cholesky

In [4]:
n = np.random.randint(10, 1001)
A = np.diag(9 * np.ones(n)) + np.diag(-4 * np.ones(n-1), k=1) + np.diag(-4 * np.ones(n-1), k=-1)
x_exact = np.ones(n)
b = np.dot(A, x_exact)
print('n:', n, '\n')
print('Matrice A: \n', A, '\n')
print('x: \n', x_exact, '\n')
print('b: \n', b, '\n')

cond1 = np.linalg.cond(A, 1)
cond2 = np.linalg.cond(A, 2)
condfro = np.linalg.cond(A, 'fro')
condinf = np.linalg.cond(A, np.inf)

print ('K(A)_1 = ', cond1, '\n')
print ('K(A)_2 = ', cond2, '\n')
print ('K(A)_fro = ', condfro, '\n')
print ('K(A)_inf = ', condinf, '\n')

# Calcolo della fattorizzazione di Cholesky
L = cholesky(A)
x_calculated = np.linalg.solve(L.T, np.linalg.solve(L, b))
print(f"Soluzione calcolata x: \n {x_calculated}")

n: 235 

Matrice A: 
 [[ 9. -4.  0. ...  0.  0.  0.]
 [-4.  9. -4. ...  0.  0.  0.]
 [ 0. -4.  9. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  9. -4.  0.]
 [ 0.  0.  0. ... -4.  9. -4.]
 [ 0.  0.  0. ...  0. -4.  9.]] 

x: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

b: 
 [5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1