In [6]:
"""Domanda 3 (Sistemi lineari). Dato un problema test di dimensioni variabili
                                    Ax = b
la cui soluzione esatta è il vettore x̄ = (1, . . . , 1)T e b è il termine noto, 
ottenuto come Ax̄ calcolare:
    • il numero di condizionamento della matrice A
    • la soluzione x del sistema lineare Ax = b mediante la fattorizzazione di Cholesky
Considerare come matrice A la matrice di Hilbert di dimensioni n tra 2 e 15."""
import numpy as np
from scipy.linalg import hilbert
from numpy.linalg import cholesky

In [11]:
n = np.random.randint(2, 16)
A = A = hilbert(n)
x_exact = np.ones(n)
b = np.dot(A, x_exact)
print('n:', n, '\n')
print('Matrice A (Hilbert): \n', A, '\n')
print('x: \n', x_exact, '\n')
print('b: \n', b, '\n')

cond1 = np.linalg.cond(A, 1)
cond2 = np.linalg.cond(A, 2)
condfro = np.linalg.cond(A, 'fro')
condinf = np.linalg.cond(A, np.inf)

print ('K(A)_1 = ', cond1, '\n')
print ('K(A)_2 = ', cond2, '\n')
print ('K(A)_fro = ', condfro, '\n')
print ('K(A)_inf = ', condinf, '\n')

# Calcolo della fattorizzazione di Cholesky
L = cholesky(A)
x_calculated = np.linalg.solve(L.T, np.linalg.solve(L, b))
print(f"Soluzione calcolata x: \n {x_calculated}")

n: 5 

Matrice A (Hilbert): 
 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]] 

x: 
 [1. 1. 1. 1. 1.] 

b: 
 [2.28333333 1.45       1.09285714 0.88452381 0.74563492] 

K(A)_1 =  943656.0000063396 

K(A)_2 =  476607.2502425855 

K(A)_fro =  480849.11699795065 

K(A)_inf =  943656.0000063627 

Soluzione calcolata x: 
 [1. 1. 1. 1. 1.]
